name: Continuous Integration

on:
    pull_request: ~
    push: ~

jobs:
    check:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Composer check
              uses: shivammathur/setup-php@v2
              run: composer validate --strict --no-check-lock
    tests:
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                include:
                    - description: 'No Symfony specified'
                      php: '7.2'
                    - description: 'No Symfony specified'
                      php: '7.3'
                    - description: 'No Symfony specified'
                      php: '7.4'
                    - description: 'No Symfony specified'
                      php: '8.0'
                    - description: 'Lowest deps'
                      php: '7.2'
                      composer_option: '--prefer-lowest'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: max[self]=0
                    - description: 'Symfony 3.4'
                      php: '7.2'
                      symfony: 3.4.*
                    - description: 'Symfony 4.4'
                      php: '7.3'
                      symfony: 4.4.*
                    - description: 'Dev deps'
                      php: '8.0'
                      dev: true
        name: PHP ${{ matrix.php }} tests (${{ matrix.description }})
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Cache
              uses: actions/cache@v2
              with: 
                  path: ~/.composer/cache/files
                  key: composer-${{ matrix.php }}-${{ matrix.symfony }}-${{ matrix.composer_option }} 
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
            - run: |
                  sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "'${{ matrix.symfony }}'"/' composer.json;
              if: matrix.symfony
            - run: composer config minimum-stability dev && composer config prefer-stable true
              if: matrix.dev
            - run: composer update --no-interaction --no-progress --ansi ${{ matrix.composer_option }}
            - run: vendor/bin/phpunit

